services:
  postgres:
    container_name: postgres-dev-gachi-fighter-bot
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-dev-gachi-fighter-bot
    image: dpage/pgadmin4:8.4
    ports:
      - "8082:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  migrator:
    container_name: postgres-migrator-dev-gachi-fighter-bot
    build:
      dockerfile: ./Dockerfile.liquibase
      context: .
    restart: no
    command:
      - sh
      - -c
      - |
        echo "apply migrations..."
        docker-entrypoint.sh --changelog-file=./changelog/changelog.xml update
    env_file:
      - .env
    # environment:
    #   - LIQUIBASE_LOG_LEVEL=FINE
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local
