name: Build & Publish Docker Images to Docker Hub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            andrew771/gachi-fighter-bot
          tags: |
            type=semver,pattern={{version}},event=tag
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-migrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            andrew771/gachi-fighter-bot-migrator
          tags: |
            type=semver,pattern={{version}},event=tag
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.liquibase
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: copy docker compose file
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.GACHI_FIGHTER_BOT_HOST }}
        username: ${{ secrets.GACHI_FIGHTER_BOT_USER }}
        password: ${{ secrets.GACHI_FIGHTER_BOT_PASSWORD }}
        source: "docker-compose.yaml"
        target: /opt/gachi-fighter-bot/
    - name: pull and restart docker compose
      uses: appleboy/ssh-action@v0.1.6
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        host: ${{ secrets.GACHI_FIGHTER_BOT_HOST }}
        username: ${{ secrets.GACHI_FIGHTER_BOT_USER }}
        password: ${{ secrets.GACHI_FIGHTER_BOT_PASSWORD }}
        script_stop: true
        script: whoami
        # script: |
        #   cd /opt/gachi-fighter-bot
        #   docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        #   docker compose -f docker-compose.yaml pull && docker compose -f docker-compose.prod.yaml up -d --force-recreate --build
        #   docker logout

